#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-unbound-init ]
do
  sleep 1
done

#if [ ! -f /tmp/state/10-unbound ]; then
#	echo 'Initialization Complete' >/tmp/state/10-unbound
#fi

s6-echo "unbound-anchor running...."
/opt/unbound/sbin/unbound-anchor -a /opt/unbound/etc/unbound/var/root.key
s6-echo "unbound-anchor finished"

s6-echo "Starting unbound"
s6-setuidgid root /opt/unbound/sbin/unbound -c /opt/unbound/etc/unbound/unbound.conf
